config/routes.rb
Rails.application.routes.draw do
root "wines#new"
resources :wines
resources :assemblies
resources :strains
resources :enologists
resources :magazines
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assembly.rb
class Assembly < ApplicationRecord
  belongs_to :wine
  belongs_to :strain

  def strain_name
    strain&.name
  end
end

app/models/enologist.rb
class Enologist < ApplicationRecord
  has_many :positions
  has_many :magazines, through: :positions

  has_many :grades
  has_many :wines, through: :grades
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :wine
  belongs_to :enologist
end

app/models/magazine.rb
class Magazine < ApplicationRecord
  has_many :positions
  has_many :enologist, through: :positions
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :enologist
  belongs_to :magazine
end

app/models/strain.rb
class Strain < ApplicationRecord
has_many :assemblies
has_many :wines, through: :assemblies
   

end

app/models/wine.rb
class Wine < ApplicationRecord

  has_many :assemblies
  has_many :strains, through: :assemblies

  has_many :grades
  has_many :enologists, through: :grades

  accepts_nested_attributes_for :assemblies

  def strains_detail

    detail = assemblies.map do |assembly|
      "#{assembly.strain_name} (#{assembly.percentage}%)"
    end
    detail.join(",")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/assemblies_controller.rb
class AssembliesController < ApplicationController
  before_action :set_assembly, only: [:show,:edit,:update,:destroy]
  def new
  end

  def create
  end

  def index
  end

  def edit
  end

  def update
  end

  def destroy
    @strain.destroy
    respond_to do |format|
      format.html { redirect_to strains_url, notice: 'Strain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def set_assembly
    @wine = Wine.find(params[:id])
  end
  def assembly_params
    params.require(:assembly).permit(:name)
  end
end

app/controllers/enologists_controller.rb
class EnologistsController < ApplicationController
  before_action :set_enologist, only: [:show,:edit,:update,:destroy]

  def new
    @enologist = Enologist.new
  end

  def create
  end

  def index
    @enologists = Enologist.all.order(:age)
  end


  def edit
  end

  def update
  end

  def destroy
    @enologist.destroy
    respond_to do |format|
      format.html { redirect_to enologists_url, notice: 'Enologist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_enologist
    @wine = Wine.find(params[:id])
  end

  def enologist_params
    params.require(:enologist).permit(:name)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enologist
      @enologist = Enologist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enologist_params
      params.require(:enologist).permit(:name, :age, :nationality, 
      positions_attributes[:magazine_id, :name, :enologist_id])
    end


end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  before_action :set_magazine, only: [:show,:edit,:update,:destroy]

  def new
  end

  def create
  end

  def index
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def set_strain
    @wine = Wine.find(params[:id])
  end

  def magazine_params
    params.require(:magazine).permit(:name)
  end

end

app/controllers/strains_controller.rb
class StrainsController < ApplicationController
  before_action :set_strain, only: [:show,:edit,:update,:destroy]

  def new
    @strain = Strain.new
  end

  def create
    @strain = Strain.new(strain_params)
    if @strain.save
      flash[:notice] = "Strain created successfully" 
      redirect_to new_strain_path     
    else
      flash[:danger]= "Error"
      render :new
    end
  end

  def index
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def set_strain
    @wine = Wine.find(params[:id])
  end

  def strain_params
    params.require(:strain).permit(:name)
  end

end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: [:show,:edit,:update,:destroy]
  def new

    @wine = Wine.new
    @strains = Strain.all
    @strains.each do |strain|
      @wine.assemblies.build(strain: strain)
    end
  end

  def create
    @wine = Wine.new(wine_params)
    if @wine.save
      flash[:notice] = "Wine created successfully" 
      redirect_to wines_path     
    else
      flash[:danger]= "Error"
      render :new
    end
  end

  def index
    @wines = Wine.all
  end

  def edit
  end

  def update
  end

  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to strains_url, notice: 'Wine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def set_wine
    @wine = Wine.find(params[:id])
  end
  def wine_params
    params.require(:wine).permit(:name,:price, assemblies_attributes: [:id, :strain_id, :wine_id, :percentage])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enologists_helper.rb
module EnologistsHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/helpers/strains_helper.rb
module StrainsHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/enologists/_form.html.erb
<%= form_with(model: enologist, local: true) do |form| %>
  <% if enologist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enologist.errors.count, "error") %> prohibited this enologist from being saved:</h2>

      <ul>
      <% enologist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :nationality %>
    <%= form.text_field :nationality %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enologists/create.html.erb
<h1>Enologists#create</h1>
<p>Find me in app/views/enologists/create.html.erb</p>

app/views/enologists/destroy.html.erb
<h1>Enologists#destroy</h1>
<p>Find me in app/views/enologists/destroy.html.erb</p>

app/views/enologists/edit.html.erb
<h1>Enologists#edit</h1>
<p>Find me in app/views/enologists/edit.html.erb</p>

app/views/enologists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enologists</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nombre </th>
      <th>Fecha Nacimiento</th>
      <th>País</th>
      <th>Trabajo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enologists.each do |enologist| %>
      <tr>
        <td><%= enologist.name %></td>
        <td><%= enologist.age %></td>
        <td><%= enologist.nationality %></td>
        <td><%= enologist.work_in %></td>
        <td><%= link_to 'Show', enologist %></td>
        <td><%= link_to 'Edit', edit_enologist_path(enologist) %></td>
        <td><%= link_to 'Destroy', enologist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enologist', new_enologist_path %>

app/views/enologists/new.html.erb
<h1>New Enologist</h1>

<%= render 'form', enologist: @enologist %>

<%= link_to 'Back', enologists_path %>

app/views/enologists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @enologist.name %>
</p>

<%= link_to 'Edit', edit_enologist_path(@enologist) %> |
<%= link_to 'Back', enologists_path %>

app/views/enologists/update.html.erb
<h1>Enologists#update</h1>
<p>Find me in app/views/enologists/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cepas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

  </head>

  <body>
  <%= render 'shared/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/magazines/create.html.erb
<h1>Magazines#create</h1>
<p>Find me in app/views/magazines/create.html.erb</p>

app/views/magazines/destroy.html.erb
<h1>Magazines#destroy</h1>
<p>Find me in app/views/magazines/destroy.html.erb</p>

app/views/magazines/edit.html.erb
<h1>Magazines#edit</h1>
<p>Find me in app/views/magazines/edit.html.erb</p>

app/views/magazines/index.html.erb
<h1>Magazines#index</h1>
<p>Find me in app/views/magazines/index.html.erb</p>

app/views/magazines/new.html.erb
<h1>Magazines#new</h1>
<p>Find me in app/views/magazines/new.html.erb</p>

app/views/magazines/update.html.erb
<h1>Magazines#update</h1>
<p>Find me in app/views/magazines/update.html.erb</p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
      <%= link_to 'Crear Cepa', new_strain_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to 'Crear Vino', new_wine_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
  </div>
</nav>

app/views/strains/_form.html.erb
<%= form_with(model:strain, local:true) do |form| %>
  <% if strain.errors.any?%>
    <div id="error_explanation">
      <h2><%= pluralize(strain.errors.count, "error")%> prohibited
      this strain from being saved:</h2>

      <ul>
        <% strain.errors.full_messages.each do |message|%>
        <li><%= message %></li>
        <%end%>
      <ul>
    </div>
<%end%>

  <div class="form-group">
    <%= form.label :name%>
    <%= form.text_field :name%>
  </div>



  <div class="actions">
    <%= form.submit%>
  </div>
<%end%>

app/views/strains/create.html.erb
<h1>Strains#create</h1>
<p>Find me in app/views/strains/create.html.erb</p>

app/views/strains/destroy.html.erb
<h1>Strains#destroy</h1>
<p>Find me in app/views/strains/destroy.html.erb</p>

app/views/strains/edit.html.erb
<h1>Strains#edit</h1>
<p>Find me in app/views/strains/edit.html.erb</p>

app/views/strains/index.html.erb
<h1>Strains#index</h1>
<p>Find me in app/views/strains/index.html.erb</p>

app/views/strains/new.html.erb
<%= render 'form', strain: @strain %>

app/views/strains/update.html.erb
<h1>Strains#update</h1>
<p>Find me in app/views/strains/update.html.erb</p>

app/views/wines/_form.html.erb
<div class="col-4 offset-4">
<h1> Crear Vino </h1>
<%= form_with(model:wine, local:true) do |form| %>
  <% if wine.errors.any?%>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error")%> prohibited
      this strain from being saved:</h2>

      <ul>
        <% wine.errors.full_messages.each do |message|%>
        <li><%= message %></li>
        <%end%>
      <ul>
    </div>
<%end%>

  <div class="form-group">
    <%= form.label :name, class: "control-label" %>
    <%= form.text_field :name, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :price, class: "control-label" %>
    <%= form.number_field :price , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.fields_for :assemblies do |assembly_form|%>
      <%= assembly_form.label assembly_form.object.strain_name, class: "control-label"%>
      <%= assembly_form.hidden_field :strain_id %>
      <%= assembly_form.number_field :percentage, class: "form-control"%>

    <% end%>
  </div> 


  <div class="actions">
    <%= form.submit "Save", class: "btn btn-success"%>
  </div>
<%end%>
</div>

app/views/wines/create.html.erb
<h1>Wines#create</h1>
<p>Find me in app/views/wines/create.html.erb</p>

app/views/wines/destroy.html.erb
<h1>Wines#destroy</h1>
<p>Find me in app/views/wines/destroy.html.erb</p>

app/views/wines/edit.html.erb
<h1>Wines#edit</h1>
<p>Find me in app/views/wines/edit.html.erb</p>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>wines</h1>
<table class="table">
  <thead>
    <tr>
      <th> Nombre </th>
      <th> Precio</th>
      <th> Cepas </th>
      <th colspan = "3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine|%>
      <tr>
        <td><%= wine.name %></td>
        <td><%= wine.price %></td>
        <td><%= wine.strains_detail %></td>
        <td><%= link_to 'Show', wine %></td>
        <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
        <td><%= link_to 'Destroy', wine, method: :delete, data: {
          confirm: 'Are you sure?'} %></td>
      </tr>
    <%end%>
  </tbody>
</table>
  

app/views/wines/new.html.erb
<div class="row">
<%= render 'form', wine: @wine %>
</div>

app/views/wines/update.html.erb
<h1>Wines#update</h1>
<p>Find me in app/views/wines/update.html.erb</p>